version: '3.4'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - "./nginx/templates:/etc/nginx/templates/:r"
      - "./nginx/static:/var/www/html/:r"
    environment:
      LISTEN_PORT: 80
      BACKEND_LOCATION: /api
      BACKEND_URL: http://kmitltelemedicineserver:5000
    depends_on:
      - kmitltelemedicineserver
  kmitltelemedicineserver:
    image: ${DOCKER_REGISTRY-}kmitltelemedicineserver
    build:
      context: .
      dockerfile: KmitlTelemedicineServer/Dockerfile
    ports:
      - "5000:5000"
    environment:
      ASPNETCORE_URLS: http://+:5000/
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/firebase_adminsdk
      ServerConfig:PathBase: /api
      TZ: Asia/Bangkok
    secrets:
      - firebase_adminsdk
secrets:
  firebase_adminsdk:
    file: ./secrets/firebase-adminsdk.json
