version: '3.8'

# noinspection ComposeUnknownKeys
include:
  - path:
      - "./docker-jitsi-meet/docker-compose.yml"
      - "./docker-compose.jitsi-override.yml"
    env_file:
      - "./secrets/jitsi-meet-password.env"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/templates:/etc/nginx/templates/:r"
      - "${APP_PATH:-/var/www/html/app/}:/var/www/app/:r"
      - "${LETS_ENCRYPT_HTTP01_ROOT:-/var/www/html/}:/var/www/http01/:r"
      - "${LETS_ENCRYPT_PATH:-/etc/letsencrypt}:/etc/letsencrypt/:r"
    environment:
      - "TZ"
      - "API_URL=http://kmitltelemedicineserver:5000"
      - "JITSIWEB_URL=http://web:80"
      - "APP_LOCATION=/app"
      - "API_LOCATION=/api"
      - "LETS_ENCRYPT_DOMAIN=${HOSTNAME}"
    depends_on:
      - kmitltelemedicineserver
      - web
    networks:
      - meet.jitsi
      - backend
  kmitltelemedicineserver:
    image: ${DOCKER_REGISTRY-}kmitltelemedicineserver
    build:
      context: .
      dockerfile: KmitlTelemedicineServer/Dockerfile
    expose:
      - "5000"
    environment:
      - "TZ"
      - "ServerConfig:PathBase=${API_LOCATION:-/api}"
      - "ServerConfig:FirebaseProjectId=${FIREBASE_PROJECTID}"
      - "ASPNETCORE_URLS=http://+:5000/"
      - "GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/firebase_adminsdk"
    secrets:
      - firebase_adminsdk
    networks:
      - backend
secrets:
  firebase_adminsdk:
    file: ./secrets/firebase-adminsdk.json
networks:
  backend:
    driver: bridge
