version: '3.8'

services:
  web:
    ports: [ ]
    expose:
      - "80"
    environment:
      - "HTTP_PORT=80"
      - "DISABLE_HTTPS=1"
      - "DISABLE_GRANT_MODERATOR=1"
      - "DISABLE_POLLS=1"
      - "DISABLE_REACTIONS=1"
      - "ENABLE_LOBBY=0"
      - "ENABLE_BREAKOUT_ROOMS=0"
      - "ENABLE_HTTP_REDIRECT=0"
      - "ENABLE_WELCOME_PAGE=0"
      - "ENABLE_CLOSE_PAGE=1"
      - "ENABLE_REQUIRE_DISPLAY_NAME=1"
      - "ENABLE_RECORDING=0"
      - "WHITEBOARD_ENABLED=0"
      - "TOOLBAR_BUTTONS=camera,chat,filmstrip,fullscreen,help,microphone,noisesuppression,profile,settings,stats,toggle-camera"
  prosody:
    environment:
      - "DISABLE_POLLS=1"
      - "ENABLE_BREAKOUT_ROOMS=0"
      - "ENABLE_RECORDING=0"
  jicofo:
    environment:
      - "ENABLE_RECORDING=0"
  jvb:
    networks:
      - default # open to internet
      - meet.jitsi
